### ISSUE TITLE
Klassendiagramm FE

### ISSUE THREAD

**Issue by JanaWengenroth** [meandor/project-aim#16]

**Comment by meandor** [comment]
make uml of discussed architecture

**Comment by Dutzel** [comment]
<img width="1002" alt="bildschirmfoto 2016-10-24 um 12 18 42" src="https://cloud.githubusercontent.com/assets/17947422/19642256/c9cce59a-99e4-11e6-99ea-6a244838ea17.png">

**Comment by Dutzel** [comment]
<img width="999" alt="bildschirmfoto 2016-10-24 um 12 28 30" src="https://cloud.githubusercontent.com/assets/17947422/19642422/70d6daee-99e5-11e6-9eaa-a9b15181ba71.png">

**Comment by Dutzel** [comment]
https://www.gliffy.com/go/html5/launch?app=1b5094b0-6042-11e2-bcfd-0800200c9a66&templateId=4218693

Anmeldung: rolandkaiser@trash-mail.com
Password: qwer1234

**Comment by Dutzel** [comment]
<img width="1039" alt="bildschirmfoto 2016-10-24 um 12 43 43" src="https://cloud.githubusercontent.com/assets/17947422/19642862/94cdded2-99e7-11e6-8b7f-62bcebc13bcd.png">

**Comment by Dutzel** [comment]
<img width="1010" alt="bildschirmfoto 2016-10-24 um 12 45 46" src="https://cloud.githubusercontent.com/assets/17947422/19642898/d473c632-99e7-11e6-862b-de9a32cce97f.png">

**Comment by meandor** [comment]
da ist noch ein rechtschreibfehler bei vendorinformation

**Comment by Dutzel** [comment]
Ist das Diagramm überhaupt schon Final?

Ich frage mich ob wir beispielsweise überhaupt eine ProductView brauchen. In meinem Verständnis haben wir eine Komponente ProductInfo, welche ein HTML-Template beinhaltet und dieses Template wird auf der AppView gerendert.

**Comment by Maltrn** [comment]
Jap, so siehts aus. Wir haben quasi nur eine View.

Am 28. Oktober 2016 um 11:53 schrieb Dutzel <notifications@github.com>:

**Comment by meandor** [comment]
jedes html template ist in angular quasi eine view

**Comment by Dutzel** [comment]
Genau, genau... Ihr seid ja auch voll die Modellierungsprofis ;) ... Gleichzeitig frage ich mich, ob wir die Views wirklich explizit im Diagramm darstellen müssen, weil wir durch unsere Technikwahl mit Angular 2 eigentlich darauf verzichten einzelne Views zu erstellen. 

Wenn ich das Diagramm so sehe, würde ich als außenstehender Frontend-Entwickler vermuten, dass ich die Views explizit anlegen müsste.

Reicht es nicht die Templates als Attribute in den Klassen darzustellen?

**Comment by meandor** [comment]
gerade das ist doch eine assoziation, also musst du die templates erstellen eine assoziation zu den klassen erstellen, also genau das, was in dem diagramm ist

**Comment by Dutzel** [comment]
<img width="1002" alt="frontenddiagramm" src="https://cloud.githubusercontent.com/assets/17947422/19847662/c28f7086-9f48-11e6-9cbe-6c1ada86e35a.png">
