### ISSUE TITLE
Backend vendor put validate descriptions

### ISSUE THREAD

**Issue by meandor** [meandor/project-aim#43]
dont count html tags!

**Comment by MaxPower9001** [comment]
add a meaningful description to issue!

**Comment by meandor** [comment]
when putting long and short description on a vendor the length of characters is count.

instead dont count html tags, because the formatting code should not count as used character length

for example filter with regex: /(<(?:.|\n)*?>|(?:\r\n|\r|\n))/gm -> in javascript
